// GENERATED by tools/build-sprites.py -- do not edit by hand.
.pragma library

var CELL = 32
var COUNT = 32
var INDEX = {
  "mati2": 0,
  "jare2": 1,
  "kaki1": 2,
  "kaki2": 3,
  "mati3": 4,
  "sleep1": 5,
  "sleep2": 6,
  "awake": 7,
  "up1": 8,
  "up2": 9,
  "down1": 10,
  "down2": 11,
  "left1": 12,
  "left2": 13,
  "right1": 14,
  "right2": 15,
  "upleft1": 16,
  "upleft2": 17,
  "upright1": 18,
  "upright2": 19,
  "dwleft1": 20,
  "dwleft2": 21,
  "dwright1": 22,
  "dwright2": 23,
  "utogi1": 24,
  "utogi2": 25,
  "dtogi1": 26,
  "dtogi2": 27,
  "ltogi1": 28,
  "ltogi2": 29,
  "rtogi1": 30,
  "rtogi2": 31
}

var CHARACTERS = ["dog", "neko", "tora"]

var POSES = {
  "stop": [
    0,
    0
  ],
  "wash": [
    1,
    0
  ],
  "scratch": [
    2,
    3
  ],
  "yawn": [
    4,
    4
  ],
  "sleep": [
    5,
    6
  ],
  "awake": [
    7,
    7
  ],
  "up": [
    8,
    9
  ],
  "down": [
    10,
    11
  ],
  "left": [
    12,
    13
  ],
  "right": [
    14,
    15
  ],
  "upleft": [
    16,
    17
  ],
  "upright": [
    18,
    19
  ],
  "dwleft": [
    20,
    21
  ],
  "dwright": [
    22,
    23
  ],
  "utogi": [
    24,
    25
  ],
  "dtogi": [
    26,
    27
  ],
  "ltogi": [
    28,
    29
  ],
  "rtogi": [
    30,
    31
  ]
}
